# Default values for post-publication-combiner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
  isResilient: "false"
  serviceAccountName: eksctl-post-publication-combiner-serviceaccount
replicaCount: 2
image:
  repository: coco/post-publication-combiner
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: 64Mi
  limits:
    memory: 256Mi
openPolicyAgentSidecar:
  name: open-policy-agent
  repository: openpolicyagent/opa
  tag: 0.62.1
  pullPolicy: IfNotPresent
env:
  PORT: 8080
  KAFKA_CONTENT_TOPIC_NAME: PostPublicationEvents
  KAFKA_METADATA_TOPIC_NAME: PostConceptAnnotations
  KAFKA_COMBINED_TOPIC_NAME: CombinedPostPublicationEvents
  KAFKA_FORCED_COMBINED_TOPIC_NAME: ForcedCombinedPostPublicationEvents
  KAFKA_CONSUMER_GROUP: post-publication-combiner
  KAFKA_LAG_TOLERANCE: 120
  DOCUMENT_STORE_BASE_URL: http://document-store-api:8080
  DOCUMENT_STORE_API_ENDPOINT: /content/{uuid}
  INTERNAL_CONTENT_API_BASE_URL: http://internal-content-api:8080
  INTERNAL_CONTENT_API_ENDPOINT: "/internalcontent/{uuid}?unrollContent=true"
  CONTENT_COLLECTION_RW_BASE_URL: http://content-collection-rw-neo4j:8080
  CONTENT_COLLECTION_RW_ENDPOINT: "/content-collection/content-package/{uuid}"
  WHITELISTED_METADATA_ORIGIN_SYSTEM_HEADERS: "http://cmdb.ft.com/systems/pac, http://cmdb.ft.com/systems/next-video-editor"
  WHITELISTED_CONTENT_TYPES: "Article, Video, MediaResource, Audio, ContentPackage, LiveBlogPackage, LiveBlogPost, ContentCollection, ImageSet, Image, Graphic, LiveEvent, Clip, ClipSet, ,"
  OPEN_POLICY_AGENT_ADDRESS: "http://localhost:8181"
  OPEN_POLICY_AGENT_POLICY_PATH: "post_publication_combiner/content_msg_evaluator"
