swagger: "2.0"

info:
  title: Post Publication Combiner
  description: Combines the PostPublication and the PostMetadataPublication events
  version: 0.0.1
  license:
    name: MIT
  contact:
    name: Universal Publishing
    email: universal.publishing@ft.com

host: api.ft.com
basePath: "/"
schemes:
  - http
  - https

definitions:
  healthcheck_check:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      ok:
        type: boolean
      severity:
        type: integer
      businessImpact:
        type: string
      technicalSummary:
        type: string
      panicGuide:
        type: string
      checkOutput:
        type: string
      lastUpdated:
        type: string
  healthcheck:
    type: object
    properties:
      schemaVersion:
        type: integer
      systemCode:
        type: string
      name:
        type: string
      description":
        type: string
      checks:
        type: array
        items:
          $ref: '#/definitions/healthcheck_check'
      ok:
        type: boolean
        enum: [true] # to enforce error if false
      severity:
        type: integer
    required:
      - ok

paths:
  /{uuid}:
    post:
      summary: UUID Force publish
      description: >
        Tries to publish into CombinedPostPublicationEvents the content and it's annotations for the given UUID
      parameters:
        - name: uuid
          in: path
          description: UUID for the content that the publish wants to be enforced
          required: true
          type: string
          x-example: a224c5d3-0f1c-49bd-b70c-c88f5d29cf60
      responses:
        200:
          description: When for the given uuid is found 'content' or 'annotations' or both of them
        400:
          description: Response expected when the uuid is wrong
        404:
          description: Response expected when the uuid is not found

  /__health:
    get:
      summary: Healthcheck
      description: Runs application healthchecks and returns FT Healthcheck style json.
      produces:
        - application/json
      responses:
        200:
          description: >
            Should always return 200 along with the output of the healthchecks - regardless
            of whether the healthchecks failed or not.
            Please inspect the overall ok property to see whether or not the application is healthy.
          schema:
            $ref: '#/definitions/healthcheck'

  /__gtg:
    get:
      summary: Good To Go
      description: Lightly healthchecks the application, and returns a 200 if it's Good-To-Go.
      produces:
          - text/plain; charset=US-ASCII
      responses:
        200:
          description: The application is healthy enough to perform all its functions correctly - i.e. good to go.
          examples:
               text/plain; charset=US-ASCII: OK
        503:
          description: >
            One or more of the applications healthchecks have failed,
            so please do not use the app. See the /__health endpoint for more detailed information.

  /__build-info:
    get:
      summary: Build Information
      description: >
        Returns application build info, such as the git repository and revision,
        the golang version it was built with, and the app release version.
      produces:
        - application/json; charset=UTF-8
      tags:
        - Info
      responses:
        200:
          description: Outputs build information as described in the summary.
          examples:
            application/json; charset=UTF-8:
              version: 0.0.1
              repository: https://github.com/Financial-Times/app-name.git
              revision: 7cdbdb18b4a518eef3ebb1b545fc124612f9d7cd
              builder: go version go1.6.3 linux/amd64
              dateTime: "20161123122615"
              